<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial_macros.xacro" />

    <!-- Materials for Color -->
    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>
    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>
    <material name="yellow">
        <color rgba="1 1 0 1"/>
    </material>
    <material name="sky_blue">
        <color rgba="0.529 0.808 0.922 1"/>
    </material>
    <material name="green">
        <color rgba="0 1 0 1"/>
    </material>
    <material name="purple">
        <color rgba="0.902 0.902 0.980 1"/>
    </material>

    <!-- Configurable Values -->
    <!-- Base -->
    <xacro:property name="base_length" value="0.11" />
    <xacro:property name="base_radius" value="0.12" />
    <!-- Link1 -->
    <xacro:property name="shoulder_length" value="0.15" />
    <xacro:property name="shoulder_radius" value="0.07" />
    <!-- Link2 -->
    <xacro:property name="upperarm_length" value="0.3" />
    <xacro:property name="upperarm_radius" value="0.06" />
    <!-- Link3 -->
    <xacro:property name="elbow_length" value="0.1" />
    <xacro:property name="elbow_radius" value="0.05" />
    <!-- Link4 -->
    <xacro:property name="forearm_length" value="0.15" />
    <xacro:property name="forearm_radius" value="0.05" />
    <!-- Gripper -->
    <xacro:property name="gripper_length" value="0.05" />

    <!-- LINKS AND JOINTS START HERE -->
    <link name="world"></link>

    <joint name="base_joint" type="fixed">
        <parent link="world"/>
        <child link="base"/>
        <origin xyz="0 1 0" rpy="0 0 0"/>
    </joint>
    <link name="base">
        <visual>
            <origin xyz="0 0 ${base_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${base_length}" radius="${base_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${base_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${base_length}" radius="${base_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1" length="${base_length}" radius="${base_radius}">
            <origin xyz="0 0 ${base_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="base">
        <material>Gazebo/White</material>
    </gazebo>

    <!-- =================================================================================== -->

    <joint name="shoulder_joint" type="revolute">
        <parent link="base"/>
        <child link="shoulder"/>
        <origin xyz="0 0 ${base_length}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-1.570796326795" upper="1.570796326795" effort="100" velocity="0.5"/>
    </joint>
    <link name="shoulder">
        <visual>
            <origin xyz="0 0 ${shoulder_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${shoulder_length}" radius="${shoulder_radius}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <visual>
            <origin xyz="0 0 ${shoulder_length}" rpy="0 -${pi/2} 0"/>
            <geometry>
                <cylinder length="${shoulder_radius*2}" radius="${shoulder_radius}"/>
            </geometry>
            <material name="red"/>
        </visual>

        <collision>
            <origin xyz="0 0 ${shoulder_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${shoulder_length}" radius="${shoulder_radius}"/>
            </geometry>
        </collision>
        <collision>
            <origin xyz="0 0 ${shoulder_length}" rpy="0 -${pi/2} 0"/>
            <geometry>
                <cylinder length="${shoulder_radius*2}" radius="${shoulder_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1" length="${shoulder_length}" radius="${shoulder_radius}">
            <origin xyz="0 0 ${shoulder_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="shoulder">
        <material>Gazebo/Red</material>
    </gazebo>

    <!-- =================================================================================== -->

    <joint name="upperarm_joint" type="revolute">
        <parent link="shoulder"/>
        <child link="upperarm"/>
        <origin xyz="0 0 ${shoulder_length}" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>
        <limit lower="-1.570796326795" upper="0.5235987755983333" effort="100" velocity="0.5"/>
    </joint>
    <link name="upperarm">
        <visual>
            <origin xyz="0 0 ${upperarm_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${upperarm_length}" radius="${upperarm_radius}"/>
            </geometry>
            <material name="yellow"/>
        </visual>
        <visual>
            <origin xyz="0 0 ${upperarm_length}" rpy="0 -${pi/2} 0"/>
            <geometry>
                <cylinder length="${upperarm_radius*2}" radius="${upperarm_radius}"/>
            </geometry>
            <material name="yellow"/>
        </visual>
        
        <collision>
            <origin xyz="0 0 ${upperarm_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${upperarm_length}" radius="${upperarm_radius}"/>
            </geometry>
        </collision>
        <collision>
            <origin xyz="0 0 ${upperarm_length}" rpy="0 -${pi/2} 0"/>
            <geometry>
                <cylinder length="${upperarm_radius*2}" radius="${upperarm_radius}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="1" length="${upperarm_length}" radius="${upperarm_radius}">
            <origin xyz="0 0 ${upperarm_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="upperarm">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <!-- =================================================================================== -->

    <joint name="elbow_joint" type="revolute">
        <parent link="upperarm"/>
        <child link="elbow"/>
        <origin xyz="0 0 ${upperarm_length}" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>
        <limit lower="-1.570796326795" upper="0.5235987755983333" effort="100" velocity="0.5"/>
    </joint>
    <link name="elbow">
        <visual>
            <origin xyz="0 0 ${elbow_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${elbow_length}" radius="${elbow_radius}"/>
            </geometry>
            <material name="sky_blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${elbow_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${elbow_length}" radius="${elbow_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1" length="${elbow_length}" radius="${elbow_radius}">
            <origin xyz="0 0 ${elbow_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="elbow">
        <material>Gazebo/SkyBlue</material>
    </gazebo>
    
    <!-- =================================================================================== -->

    <joint name="forearm_joint" type="revolute">
        <parent link="elbow"/>
        <child link="forearm"/>
        <origin xyz="0 0 ${elbow_length}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-3.14159265359" upper="3.14159265359" effort="100" velocity="0.5"/>
    </joint>
    <link name="forearm">
        <visual>
            <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${forearm_length}" radius="${forearm_radius}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${forearm_length}" radius="${forearm_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1" length="${forearm_length}" radius="${forearm_radius}">
            <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="forearm">
        <material>Gazebo/Green</material>
    </gazebo>

    <!-- =================================================================================== -->

    <joint name="gripper_joint" type="fixed">
        <parent link="forearm"/>
        <child link="gripper"/>
        <origin xyz="0 0 ${forearm_length}" rpy="0 0 0"/>
    </joint>
    <link name="gripper">
        <visual>
            <origin xyz="0 0 ${gripper_length/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${gripper_length} ${gripper_length} ${gripper_length}"/>
            </geometry>
            <material name="purple"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${gripper_length/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${gripper_length} ${gripper_length} ${gripper_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="1" x="${gripper_length}" y="${gripper_length}" z="${gripper_length}">
            <origin xyz="0 0 ${gripper_length/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    <gazebo reference="gripper">
        <material>Gazebo/Purple</material>
    </gazebo>

    <!-- =================================================================================== -->

</robot>
