<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">

    <!-- Configurable Values -->
    <!-- Base -->
    <xacro:property name="base_length" value="0.1" />
    <xacro:property name="base_radius" value="0.1" />
    <!-- Link1 -->
    <xacro:property name="shoulder_length" value="0.1" />
    <xacro:property name="shoulder_radius" value="0.07" />
    <!-- Link2 -->
    <xacro:property name="upperarm_length" value="0.2" />
    <xacro:property name="upperarm_radius" value="0.06" />
    <!-- Link3 -->
    <xacro:property name="elbow_length" value="0.05" />
    <xacro:property name="elbow_radius" value="0.05" />
    <!-- Link4 -->
    <xacro:property name="forearm_length" value="0.1" />
    <xacro:property name="forearm_radius" value="0.05" />
    <!-- Gripper -->
    <xacro:property name="gripper_length" value="0.05" />

    <!-- LINKS AND JOINTS START HERE -->
    <link name="world"></link>

    <joint name="base_joint" type="fixed">
        <parent link="world"/>
        <child link="base"/>
        <origin xyz="0 1 0" rpy="0 0 0"/>
    </joint>
    <link name="base">
        <visual>
            <origin xyz="0 0 ${base_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${base_length}" radius="${base_radius}"/>
            </geometry>
        </visual>
    </link>

    <joint name="shoulder_joint" type="revolute">
        <parent link="base"/>
        <child link="shoulder"/>
        <origin xyz="0 0 ${base_length}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-3.1416" upper="3.1416" effort="100" velocity="0.1"/>
    </joint>
    <link name="shoulder">
        <visual>
            <origin xyz="0 0 ${shoulder_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${shoulder_length}" radius="${shoulder_radius}"/>
            </geometry>
        </visual>
    </link>

    <joint name="upperarm_joint" type="revolute">
        <parent link="shoulder"/>
        <child link="upperarm"/>
        <origin xyz="0 0 ${shoulder_length}" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>
        <limit lower="-3.1416" upper="3.1416" effort="100" velocity="0.1"/>
    </joint>
    <link name="upperarm">
        <visual>
            <origin xyz="0 0 ${upperarm_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${upperarm_length}" radius="${upperarm_radius}"/>
            </geometry>
        </visual>
    </link>

    <joint name="elbow_joint" type="revolute">
        <parent link="upperarm"/>
        <child link="elbow"/>
        <origin xyz="0 0 ${upperarm_length}" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>
        <limit lower="-3.1416" upper="3.1416" effort="100" velocity="0.1"/>
    </joint>
    <link name="elbow">
        <visual>
            <origin xyz="0 0 ${elbow_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${elbow_length}" radius="${elbow_radius}"/>
            </geometry>
        </visual>
    </link>

    <joint name="forearm_joint" type="revolute">
        <parent link="elbow"/>
        <child link="forearm"/>
        <origin xyz="0 0 ${elbow_length}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-3.1416" upper="3.1416" effort="100" velocity="0.1"/>
    </joint>
    <link name="forearm">
        <visual>
            <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${forearm_length}" radius="${forearm_radius}"/>
            </geometry>
        </visual>
    </link>

    <joint name="gripper_joint" type="fixed">
        <parent link="forearm"/>
        <child link="gripper"/>
        <origin xyz="0 0 ${forearm_length}" rpy="0 0 0"/>
    </joint>
    <link name="gripper">
        <visual>
            <origin xyz="0 0 ${gripper_length/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${gripper_length} ${gripper_length} ${gripper_length}"/>
            </geometry>
        </visual>
    </link>
</robot>
