controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    # List of controllers to load
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    

joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_joint
      - upperarm_joint
      - elbow_joint
      - forearm_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    

    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20
